Contact Page Modification
codinganddecoding/temp-website pull request #2
Opened 2020-07-12 06:47 UTC by iamrohitsuthar

Contact Page

2020-07-12 06:57 UTC, saglaniharsh requested changes

2020-07-12 06:57 UTC, ashawe commented on assets/css/style.css
> +.heart {
No need to do this use <i class="fa fa-heart"></>

2020-07-12 06:57 UTC, ashawe commented on assets/css/style.css
> +.btn-primary:hover {
effect is good. try to change color. Pink is does not look that good

2020-07-12 06:57 UTC, ashawe commented on contact.html
> +   <title>Contact Page </title>
Change to "Contact Us"

2020-07-12 06:57 UTC, ashawe commented on contact.html
> +                              <a href="elements.html" class="">Elements</a>
Remove this or copy nav from #1

2020-07-12 06:57 UTC, ashawe commented on contact.html
> +                           and cleaning data. No complex SQL queries required. Just the answers <br> teams need to make
copy description from #1 too

2020-07-12 06:57 UTC, ashawe commented on contact.html
> +                                    <p><i class="fa fa-phone text-center"></i> <strong>Phone:</strong> (+91) 1234 5678
Let's use a real phone number

2020-07-12 06:57 UTC, ashawe commented on contact.html
> +                                          class="email_color_site">info@codinganddecoding.com</a></p>
and also a our real email until we get paid hosting with the domain and custom email

2020-07-12 06:58 UTC, ashawe commented
Also, from next time please make sure to select project on the right side while submitting pr

2020-07-12 07:44 UTC, iamrohitsuthar commented
Okay, Done with the requested changes.
Now please check!

2020-07-12 09:42 UTC, saglaniharsh approved these changes

2020-07-12 09:48 UTC, saglaniharsh requested changes
@iamrohitsuthar Just one more thing. Please update the footer with what's in #1 otherwise it will be overwritten when the branch is merged. Just keep the social icons and use rest from #1 
Thanks.

2020-07-13 08:42 UTC, iamrohitsuthar commented
okay

2020-07-13 08:48 UTC, iamrohitsuthar commented
Now please check

2020-07-13 16:20 UTC, saglaniharsh approved these changes

2020-07-13 16:20 UTC, merged