Modify About Us Page
codinganddecoding/temp-website pull request #5
Opened 2020-07-16 18:36 UTC by iamrohitsuthar

2020-07-17 05:11 UTC, ashawe commented on about.html
> +                  <p class="services-right-text">Our mission is to help enterprises accelerate adoption of new technologies, untangle complex issues that always emerge during digital evolution, and o
Our mission is to help enterprises accelerate adoption of new technologies, untangle complex issues that always emerge during digital evolution, and orchestrate ongoing innovation. Whether it is a consumer-oriented app or a transformative enterprise-class solution, we believe to lead the process from ideation and concept to delivery, and provide ongoing support.

2020-07-17 05:36 UTC, ashawe commented on about.html
> +                        <a id="#services" href="contact.html" class="btn btn-primary  wow fadeInUp  js-scroll-trigger"
change button style

2020-07-17 05:37 UTC, saglaniharsh requested changes
A little change in the text of mission & vision and change the button above the footer;
And please use other image from unsplash.com

2020-07-19 16:21 UTC, iamrohitsuthar commented
> A little change in the text of mission & vision and change the button above the footer;
> And please use other image from unsplash.com

Hey, It would be great if you please share the URL of the images. I had previously searched but unable to find any relevant images.

2020-07-19 17:34 UTC, ashawe commented
> 
> 
> > A little change in the text of mission & vision and change the button above the footer;
> > And please use other image from unsplash.com
> 
> Hey, It would be great if you please share the URL of the images. I had previously searched but unable to find any relevant images.

[Select appropriate images related to tech from these](https://unsplash.com/s/photos/corporate)

2020-07-20 06:34 UTC, iamrohitsuthar commented
Please check now!

2020-07-20 06:41 UTC, saglaniharsh approved these changes
Just change the envelope-o to envelope icon and done.

2020-07-20 06:54 UTC, merged